### ISSUE TITLE
Frequency/Tone of noise synths

### ISSUE THREAD

**Issue by AlecTroemel** [Kyle-Shanks/Aeronaut#1]
First of all thank you for this wonderful project, sounds great!

I was playing with the 2 noise synths (channels E and F), and they seem to be stuck on the same tone / frequency, no matter what note and octave I send. Am I missing something simple, or is that a current limitation?

**Comment by Kyle-Shanks** [comment]
Hey Alec,

Yes that’s a limitation of the noise channels unfortunately. I built them
to just produce random white noise so they won’t change in pitch or
anything. I typically used the gain envelope and filter to shape the sound
of them a bit.

Hope this helps
