### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by pseudofakee** [Kyle-Shanks/Aeronaut#3]
Hi there,

Just come across this as a fan of pilot. Great job :)

Is it possible to get a linux build?

Cheers,
Joseph

**Comment by pseudofakee** [comment]
Eh, I just built it in a container :)

**Comment by Kyle-Shanks** [comment]
Whoops, completely missed this. Yea building in a container could work. Can also import electron-packager package and build using that. 👍
